/**
 * Telemetry digest (mirrors VBAtoPython).
 *
 * Reads `usage_events` (rows where site = 'matlab') from the shared Supabase
 * project and produces a markdown digest:
 *   - Top 10 features by count (last 7 days) + week-over-week delta
 *   - Top 10 warnings by count (last 7 days) + week-over-week delta
 *   - Conversion success rate
 *   - Lines-bucket distribution
 *   - Mode distribution (paste / upload / batch)
 *
 * Run:  npx tsx scripts/telemetry-digest.ts            # prints to stdout
 *       npx tsx scripts/telemetry-digest.ts --write    # also overwrites docs/telemetry-digest-latest.md
 *
 * Needs SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (same vars the app uses).
 * No SDK — PostgREST over fetch.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'

const SUPABASE_URL = process.env.SUPABASE_URL || ''
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
const SITE = 'matlab'

interface Counted { id: string; count: number }
interface UsageEvent {
  session_id: string
  ts: string
  event_type: string
  target: string | null
  lines_bucket: string | null
  features: Counted[] | null
  warnings: Counted[] | null
}

const DAY = 86_400_000

async function fetchEvents(sinceIso: string): Promise<UsageEvent[]> {
  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    throw new Error('SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set')
  }
  const url =
    `${SUPABASE_URL}/rest/v1/usage_events` +
    `?select=session_id,ts,event_type,target,lines_bucket,features,warnings` +
    `&site=eq.${SITE}` +
    `&ts=gte.${sinceIso}&order=ts.desc&limit=100000`
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_SERVICE_KEY, Authorization: `Bearer ${SUPABASE_SERVICE_KEY}` },
  })
  if (!res.ok) throw new Error(`Supabase query failed: ${res.status} ${await res.text()}`)
  return res.json()
}

function tally(events: UsageEvent[], field: 'features' | 'warnings'): Map<string, number> {
  const m = new Map<string, number>()
  for (const e of events) for (const c of e[field] ?? []) m.set(c.id, (m.get(c.id) ?? 0) + c.count)
  return m
}

function countBy(events: UsageEvent[], key: (e: UsageEvent) => string | null): Map<string, number> {
  const m = new Map<string, number>()
  for (const e of events) {
    const k = key(e) ?? '(none)'
    m.set(k, (m.get(k) ?? 0) + 1)
  }
  return m
}

function topTable(title: string, cur: Map<string, number>, prev: Map<string, number>): string {
  const rows = [...cur.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10)
  if (!rows.length) return `### ${title}\n\n_None._\n`
  const lines = [`### ${title}`, '', '| # | id | count | WoW |', '|---|----|------:|----:|']
  rows.forEach(([id, count], i) => {
    const before = prev.get(id) ?? 0
    const wow = before === 0 ? 'new' : `${count - before >= 0 ? '+' : ''}${count - before}`
    lines.push(`| ${i + 1} | \`${id}\` | ${count} | ${wow} |`)
  })
  return lines.join('\n') + '\n'
}

function distTable(title: string, m: Map<string, number>, total: number): string {
  const rows = [...m.entries()].sort((a, b) => b[1] - a[1])
  if (!rows.length) return `### ${title}\n\n_None._\n`
  const lines = [`### ${title}`, '', '| value | events | share |', '|-------|-------:|------:|']
  for (const [v, n] of rows) {
    const share = total > 0 ? `${Math.round((n / total) * 100)}%` : '0%'
    lines.push(`| \`${v}\` | ${n} | ${share} |`)
  }
  return lines.join('\n') + '\n'
}

function buildDigest(cur: UsageEvent[], prev: UsageEvent[]): string {
  const today = new Date().toISOString().slice(0, 10)
  const sessions = new Set(cur.map((e) => e.session_id)).size
  const successes = cur.filter((e) => e.event_type === 'convert_success').length
  const total = cur.length
  const rate = total > 0 ? Math.round((successes / total) * 100) : 0

  const parts = [
    `# Telemetry digest (MATLABtoPython) — ${today}`,
    '',
    `_Auto-generated by \`scripts/telemetry-digest.ts\` from \`usage_events\` where site='matlab' (consented, anonymous). Window: last 7 days; WoW compares to the prior 7._`,
    '',
    '## Summary',
    '',
    `- **Events (7d):** ${total}  (prior 7d: ${prev.length})`,
    `- **Distinct sessions:** ${sessions}`,
    `- **Conversion success rate:** ${rate}%  (${successes}/${total})`,
    '',
    topTable('Top features (7d)', tally(cur, 'features'), tally(prev, 'features')),
    topTable('Top warnings (7d)', tally(cur, 'warnings'), tally(prev, 'warnings')),
    distTable('Lines-bucket distribution', countBy(cur, (e) => e.lines_bucket), total),
    distTable('Mode distribution', countBy(cur, (e) => e.target), total),
  ]
  return parts.join('\n')
}

async function main() {
  const now = Date.now()
  const cur = await fetchEvents(new Date(now - 7 * DAY).toISOString())
  const all = await fetchEvents(new Date(now - 14 * DAY).toISOString())
  const prevCutoff = now - 7 * DAY
  const prev = all.filter((e) => new Date(e.ts).getTime() < prevCutoff)

  const md = buildDigest(cur, prev)
  process.stdout.write(md + '\n')

  if (process.argv.includes('--write')) {
    const out = join(process.cwd(), 'docs', 'telemetry-digest-latest.md')
    mkdirSync(dirname(out), { recursive: true })
    writeFileSync(out, md + '\n', 'utf-8')
    process.stderr.write(`\n[wrote ${out}]\n`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
